# 基础镜像
FROM nginx
# author
MAINTAINER dms

# 挂载目录
VOLUME /home/dms/projects/dms-ui
# 创建目录
RUN mkdir -p /home/dms/projects/dms-ui
# 指定路径
WORKDIR /home/dms/projects/dms-ui
# 复制conf文件到路径
COPY ./conf/nginx.conf /etc/nginx/nginx.conf
# 复制html文件到路径
COPY ./html/dist /home/dms/projects/dms-ui
