# 基础镜像
FROM  openjdk:8-jre
# author
MAINTAINER dms

# 挂载目录
VOLUME /home/dms
# 创建目录
RUN mkdir -p /home/dms
# 指定路径
WORKDIR /home/dms
# 复制jar文件到路径
COPY ./jar/dms-gateway.jar /home/dms/dms-gateway.jar
# 启动网关服务
ENTRYPOINT ["java","-jar","dms-gateway.jar"]