# 基础镜像
FROM  openjdk:8-jre
# author
MAINTAINER dms

# 挂载目录
VOLUME /home/dms
# 创建目录
RUN mkdir -p /home/dms
# 指定路径
WORKDIR /home/dms
# 复制jar文件到路径
COPY ./jar/dms-visual-monitor.jar /home/dms/dms-visual-monitor.jar
# 启动系统服务
ENTRYPOINT ["java","-jar","dms-visual-monitor.jar"]